<!DOCTYPE html>
<html>
<head>
<title>C云 | 主页</title>
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<meta charset="utf8">
<?php echo Phalcon\Tag::stylesheetLink('css/bootstrap.min.css')?>
</head>
<body>
<h1>Hello,Album.</h1>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<?php echo Phalcon\Tag::javascriptInclude("js/jquery.min.js"); ?>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<?php echo Phalcon\Tag::javascriptInclude("js/bootstrap.min.js"); ?>

</body>
</html>