<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Album | 音乐</title>
<meta name="viewport"
	content="width=1000, initial-scale=1.0, maximum-scale=1.0">
<link href="/css/bootstrap.css" rel="stylesheet">
<link href="/css/flat-ui.css" rel="stylesheet">
<link href="/css/home.css" rel="stylesheet">
<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
<!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<div class="row myrow">
		<div class="col-sm-3 col-md-2 sidebar">
			<ul class="nav nav-sidebar">
				<li >
					<a href="/home">Home</a>
				</li>
				<li >
					<div class="head" style="background-image: url(/img/user.jpg);">
						
					</div>
				</li>
				<li>
					<a href="/picture"><span class="fui-photo"></span>&nbsp;&nbsp;&nbsp;&nbsp; 图 &nbsp;&nbsp;&nbsp;片</a>
				</li>
				<li>
					<a href="/video"><span class="fui-video"></span>&nbsp;&nbsp;&nbsp;&nbsp; 视 &nbsp;&nbsp;&nbsp;频</a>
				</li>
				<li class="active">
					<a href="/music"><span class="glyphicon glyphicon-music"></span>&nbsp;&nbsp;&nbsp;&nbsp; 音&nbsp;&nbsp;&nbsp;乐</a>
				</li>
			</ul>
			

		</div>
		<div class="col-sm-9  col-md-10  main"></div>
	</div>
	<div class="row myrow">
		<footer>
			<div class="timer">
				<div class="timeline">
					Time Line
				</div><a href="#">
				<div class="lastmonth">
					4月
				</div></a>
				<a href="#">
				<div class="month">
					5月
				</div></a>
				<div class="day">
					<table>
						<tr>
							<td><a href="#">1</a></td>
							<td><a href="#">2</a></td>
							<td><a href="#">3</a></td>
							<td><a href="#">4</a></td>
							<td><a href="#">5</a></td>
						</tr>
					</table>
				</div><a href="#">
				<div class="nextmonth">
					6月
				</div>
				</a>
			</div>
			<div class=" declaration">
				<p class="text-center">Copyright © 2013-future Power by hongker ℡12345678</p>
			</div>
		</footer>


	</div>

	<?php $this->partial("common/footer") ?>
</body>
</html>
