<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Album | Register</title>
    <meta name="viewport" content="width=1000, initial-scale=1.0, maximum-scale=1.0">
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/flat-ui.css" rel="stylesheet">
    <link href="/css/register.css" rel="stylesheet">
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <div class="main">
  	<div class="main-body">
  		
  		<form method="post" action="/register/add">
  		<div class="login-form"  >
  			
            <div class="form-group ">
              <input type="text" name="username" class="form-control login-field "  placeholder="Enter your name" id="register-name" required="required"
				autofocus="autofocus"/>
              <label class="login-field-icon fui-user" for="register-name"></label>
            </div>
            
            <div class="form-group ">
              <input type="email" name="email" class="form-control login-field "  placeholder="Enter your Email" id="register-email" required="required"
				autofocus="autofocus"/>
              <label class="login-field-icon fui-mail" for="register-email"></label>
            </div>

            <div class="form-group ">
              <input type="password" name="password" class="form-control login-field"  placeholder="Your Password" id="register-pass" required="required"/>
              <label class="login-field-icon fui-lock" for="register-pass"></label>
            </div>
            
            <div class="form-group ">
              <input type="password" name="repeatpassword" class="form-control login-field"  placeholder="Password Confirm" id="repeatpassword" required="required"/>
              <label class="login-field-icon fui-lock" for="register-pass"></label>
              <p> <?php $this->flashSession->output(); ?></p>
            </div>

            <button type="submit" class="btn btn-success btn-lg btn-block" >Sign up</button>
           	
          </div>
          
          </form>
          </div>
          
  		
  		
  	</div>
  		
  		
  

  
<?php $this->partial("common/footer") ?>
  </body>
</html>