<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Album | Register</title>
    <meta name="viewport" content="width=1000, initial-scale=1.0, maximum-scale=1.0">
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/flat-ui.css" rel="stylesheet">
    <link href="/css/register.css" rel="stylesheet">
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="/js/html5shiv.js"></script>
      <script src="/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <div class="main">
  	<div class="main-body">
  		
  		<form method="post" action="/login/auth">
  		<div class="login-form"  >
  			
            <div class="form-group has-success">
              <input type="text" name="username" class="form-control login-field "  placeholder="Enter your name" id="register-name" required="required"
				autofocus="autofocus"/>
              <label class="login-field-icon fui-user" for="register-name"></label>
            </div>
            
            <div class="form-group has-success">
              <input type="email" name="email" class="form-control login-field "  placeholder="Enter your Email" id="register-email" required="required"
				autofocus="autofocus"/>
              <label class="login-field-icon fui-mail" for="register-email"></label>
            </div>

            <div class="form-group has-success">
              <input type="password" name="password" class="form-control login-field"  placeholder="Password" id="register-pass" required="required"/>
              <label class="login-field-icon fui-lock" for="register-pass"></label>
            </div>

            <button tyle="submit" class="btn btn-success btn-lg btn-block" >Sign In</button>
           
          </div>
          
          </form>
          </div>
  		
  		
  	</div>
  		
  		
  

  
  
<!-- Load JS here for greater good =============================-->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script src="/js/jquery.ui.touch-punch.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-select.js"></script>
    <script src="/js/bootstrap-switch.js"></script>
    <script src="/js/flatui-checkbox.js"></script>
    <script src="/js/flatui-radio.js"></script>
    <script src="/js/jquery.tagsinput.js"></script>
    <script src="/js/jquery.placeholder.js"></script>
    <script src="/js/jquery.stacktable.js"></script>
    <script src="/js/video.js"></script>
    <script src="/js/application.js"></script>
  </body>
</html>